from sim_objdict import SimObjectDict


class SimController():
    """     This module defines the SimController class. This object will initiate and contain the components of
        this simulation. The main components are the SimModel, the SimViewer and the SimData objects.
        The SimModel performs the astrodynamic calculations to determine the state of bodies in the system.
        The SimViewer generates a graphical representation of selected portions of the SimModel outputs.
        The SimData consists of shared memory regions to serve as buffers for the state information of system bodies
        generated by the SimModel process. Two identical buffers are created such that while the state data is
        animated over the time interval, the other is being rapidly populated with the state data of the
        subsequent time interval. This provides a continuous stream of states that can be rendered at a frame rate
        approaching real time animation. This class will orchestrate this process, execute user inputs and keep
        sufficient logs to track down subtle errors that may arise.
    """
    def __init__(self):
        self.sim_model = SimObjectDict()
        print(f"Created {self.sim_model} of type {type(self.sim_model)}")


if __name__ == "__main__":
    s_ctrl = SimController()
    print(f"Created {s_ctrl} of type {type(s_ctrl)}")